#spring的配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
    url: jdbc:mysql://localhost:3306/db_hospital
    username: root
    password: 123456
    #配置端口号
server:
  port: 9090

logging:
  level:
    com.jgp.backspring.mapper: debug
